<?php $this->headTitle()->prepend($this->translate('Contact us')); ?>
<?php $this->headMeta()->setName('keywords', 'contact us, help, helpdesk, issue, fix'); ?>
<?php $this->headMeta()->setName('description', $this->translate('For questions, suggestions or compliments, you can contact our team by using this online form. We promise to get back to you as soon as possible.')); ?>

<div class="container">
    <div class="row header">
    	<div class="col-lg-12">
    		<h2><?php echo $this->translate('Contact us') ?></h2>
    		<p><?php echo $this->translate('For questions, suggestions or compliments, you can contact our team by using this online form. We promise to get back to you as soon as possible.') ?></p>
    	</div>
        
        <?php if ($this->error): ?>
            <div class="col-lg-12">
    		<div class="alert alert-danger">
                    <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.')?>
                </div>
    	</div>
        <?php endif ?>
    </div>
    
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('contact/process'));
        $form->setAttribute('method', 'post');
        
        echo $this->form()->openTag($form);
    ?>
    
    <div class="row">
    	<div class="col-lg-12">
    	    <div class="form-group">
                <?php echo $this->formLabel($form->get('from')); ?>
                <?php echo $this->formElement($form->get('from')->setAttributes(array('class' => 'form-control'))); ?>
                <?php echo $this->formElementErrors($form->get('from')); ?>
            </div>
    	</div>
    	<div class="col-lg-12">
    	    <div class="form-group">
                <?php echo $this->formLabel($form->get('subject')); ?>
                <?php echo $this->formElement($form->get('subject')->setAttributes(array('class' => 'form-control'))); ?>
                <?php echo $this->formElementErrors($form->get('subject')); ?>
            </div>
    	</div>
    	<div class="col-lg-12">
    	    <div class="form-group">
                <?php echo $this->formLabel($form->get('body')); ?>
                <?php echo $this->formElement($form->get('body')->setAttributes(array('rows' => '15', 'class' => 'form-control'))); ?>
                <?php echo $this->formElementErrors($form->get('body')); ?>
            </div>
    	</div>
    	<div class="col-lg-12">
    	    <div class="form-group">
                <?php echo $this->formLabel($form->get('captcha')); ?>
                <?php echo $this->formElement($form->get('captcha')); ?>
                <?php echo $this->formElementErrors($form->get('captcha')); ?>
            </div>
    	</div>
        <?php echo $this->formElement($form->get('csrf')); ?>
        <?php echo $this->formElementErrors($form->get('csrf')); ?>
    </div>
    
     <div class="text-right">
        <?php echo $this->formElement($form->get('Send')->setAttributes(array('class' => 'btn btn-success'))); ?>
    </div>
    
    <?php echo $this->form()->closeTag()?>
</div>