<?php 
$this->headTitle()->prepend($this->translate('Contact'));
$this->headTitle()->prepend($this->translate('Thank You!'));
?>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <section class="contact">
                <h2><?php echo $this->translate('Thank You!'); ?></h2>
                <p>
                    <?php echo $this->translate('Your message has been sent!'); ?>
                </p>
            </section>
        </div>
    </div>
</div>