<?php $this->headTitle()->prepend($this->translate('Category - List of the product categories')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'process')));
    $form->setAttribute('name', 'attributeset');
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>

<div class="row header">
    <div class="col-lg-10">
        <div class="page-header">
            <h1><i class="fa fa-list"></i> <?php echo $this->translate('Category') ?> <small><?php echo $this->translate('Handle the categories') ?></small></h1>
            <?php echo $this->translate('This is the list of the categories of this site.') ?>
        </div>
    </div>
    <?php if ($this->error): ?>
        <div class="col-lg-12">
            <div class="alert alert-warning">
                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
            </div>
        </div>
    <?php endif ?>
</div>


<div class="row">
    <div class="col-lg-4">
    	<div class="row">
        	<div class="col-lg-4">
        		<h5><?php echo $this->translate('Product Category')?></h5>
        	</div>
        	<div class="col-lg-8 text-right">
        		<a class="btn btn-danger btn-sm " id="btnCategoryDelete"><?php echo $this->translate('Delete Category')?></a>
        		<a class="btn btn-success btn-sm " id="btnCategoryCreate"><?php echo $this->translate('New Category')?></a> 
    		</div>
    	</div>
    	<div id="categorytree" name="selNodes"></div>
    </div>
    
    <div class="col-lg-8">
        <div class="tabbable" id="tabs">
			<ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#tab10"><?php echo $this->translate('Main');?></a></li> 
			</ul>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab10">
                    <div class="row">    
                        <div class="col-lg-12">
                            <div class="form-set">
    	                        <?php echo $this->formLabel($form->get('name')); ?>
    	                        <?php echo $this->formElement($form->get('name')); ?>
    	                        <?php echo $this->formElementErrors($form->get('name')); ?>
    	                    </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->formElement($form->get('id')); ?>
<?php echo $this->form()->closeTag() ?>
