<?php echo $this->headTitle($this->settings('metatitle'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php foreach ($this->Languagecodes() as $code => $translation): ?>
   <?php $this->headLink(array('rel' => 'alternate', 'href' => "http://" . $_SERVER['HTTP_HOST'] . '/' . $code, 'hreflang'=> $code)); ?>
<?php endforeach; ?>
<?php $this->headLink(array('rel' => 'alternate', 'href' => "http://" . $_SERVER['HTTP_HOST'], 'hreflang'=> 'x-default')); ?>
    
<?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/application.css'); ?>

<?php $this->inlineScript()->prependFile($this->basePath() . '/js/application.js'); ?>
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/base.js'); ?>

<?php echo $this->headLink(); ?>
<?php echo $this->headMeta() ?>
<?php echo $this->settings('headscript')?>
<?php echo $this->settings('ganalytics')?>