
<?php echo $this->headTitle($this->settings('metatitle'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()
    ->appendName('keywords', $this->settings('metakeywords'))
    ->appendName('description', $this->settings('metadescription'))
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- the css styles -->
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/application.css'); ?>
<!-- the javascript -->
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/application.js'); ?>

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) ?>
<?php echo $this->settings('headscript')?>


<!-- Google Analitycs code -->
<?php echo $this->settings('ganalytics')?>

