<div class="container">
    <div class="row header">
        <div class="col-lg-12">
            <h3><?php echo sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()); ?></h3>
            <small><?php echo sprintf($this->translate("Change the %s's email address"), $this->zfcUserDisplayName()); ?></small>
        </div>    
    </div>
    
    <?php if ($status === true) : ?>
        <div class="row"><div class="col-lg-12"><div class="alert alert-success"><?php echo $this->translate('Email changed successfully.');?></div></div></div>
    <?php elseif ($status === false) : ?>
        <div class="row"><div class="col-lg-12"><div class="alert alert-danger"><?php echo $this->translate('Unable to update your email. Please try again.'); ?></div></div></div>
    <?php endif; ?>
    
    <?php
        $form = $this->changeEmailForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changeemail'));
        $form->setAttribute('method', 'post');
    ?>
    
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->form()->openTag($form) ?>
            <?php echo $this->FormElement($form->get('identity')) ?>
            
            <?php echo $this->formLabel($form->get('newIdentity')) ?>
            <div style="margin-bottom: 25px" class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                <?php echo $this->FormElement($form->get('newIdentity')->setAttributes(array('class' => 'form-control', 'placeholder'=>$this->translate('type here the new email address')))) ?>
            </div>
            <?php echo $this->formElementErrors($form->get('newIdentity')) ?>
            
            <?php echo $this->formLabel($form->get('newIdentityVerify')) ?>
            <div style="margin-bottom: 25px" class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                <?php echo $this->FormElement($form->get('newIdentityVerify')->setAttributes(array('class' => 'form-control', 'placeholder'=>$this->translate('type again the new email address')))) ?>
            </div>
            <?php echo $this->formElementErrors($form->get('newIdentityVerify')) ?>
            
            <?php echo $this->formLabel($form->get('credential')) ?>
            <div style="margin-bottom: 25px" class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                <?php echo $this->FormElement($form->get('credential')->setAttributes(array('class' => 'form-control', 'placeholder'=>$this->translate('type here your password')))) ?>
            </div>
            <?php echo $this->formElementErrors($form->get('credential')) ?>
            
    
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
        <?php endif ?>
        
        <div class="form-group">
                <input class="btn btn-success" type="submit" value="<?php echo $this->translate('Save') ?>" />
        </div>
        <div class="form-group">
            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                <a href="/user"><?php echo $this->translate('Go back')?></a>
            </div>
        </div>    
    <?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>