<div class="row header">
    <div class="col-lg-12">
        <h3><?php echo $this->translate('Create a new profile') ?></h3>
        <p><?php echo $this->translate('Register your new profile by the registration form.') ?></p>
    </div>
</div>

<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
    <?php foreach ($form as $element): ?>
        <div class="form-group">
            <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                <?php echo $this->formLabel($element) ?>
            <?php endif ?>
            <?php if ($element instanceof Zend\Form\Element\Button): ?>
                <?php echo $this->formButton($element->setAttributes(array('class' => 'btn btn-success'))) ?>
            <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
            <?php else: ?>
                <?php echo $this->formInput($element->setAttributes(array('class' => 'form-control'))) . $this->formElementErrors($element) ?>
            <?php endif ?>
        </div>
    <?php endforeach ?>
    </dl>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>
