<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <?php echo $this->partial('partial/head.phtml'); ?> 
    </head>
    <body>
        <?php echo $this->partial('partial/header.phtml'); ?> 
        <?php echo $this->flashMessage(); ?>
        <?php echo $this->content; ?>
        
        <?php echo $this->partial('footer'); ?> 
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
