<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />	
		<title><?php echo $this->record['subject'] ?></title>
		<!--general stylesheet-->
		<style type="text/css">
			p { padding: 0; margin: 0; }
			h1, h2, h3, p, li { font-family: Helvetica Neue, Helvetica, Arial, sans-serif; }
			td { vertical-align:top;}
			ul, ol { margin: 0; padding: 0;}
			.heading {
				border-radius: 3px;
				-webkit-border-radius: 3px;
				-moz-border-radius: 3px;
				-khtml-border-radius: 3px;
				-icab-border-radius: 3px;
			}
		</style>
	</head>
	<body marginheight="0" topmargin="0" marginwidth="0" leftmargin="0" background="" style="margin: 0px; background-color: #ffffff;" bgcolor="#ffffff">
		<table cellspacing="0" border="0" cellpadding="0" width="100%">
			<tbody>
				<tr valign="top">
					<td><!--container-->
						<table cellspacing="0" cellpadding="0" border="0" align="center" width="750" bgcolor="#ffffff">
							<tbody>
								<tr>
									<td valign="top" bgcolor="#ffffff" align="center">
										<table cellspacing="0" border="0" cellpadding="0" width="700">
											<tbody>
												<tr>
													<td valign="top" height="37" style="height: 37px;">&nbsp;</td>
												</tr>
												<tr>
													<td valign="top" colspan="2" style="text-align: left;">
														<h1 style="margin: 0; padding: 0; font-size: 22px; color: #fd2323; font-weight: bold;"><?php echo $this->record['subject'] ?></h1>
														<h2 class="date" style="margin: 0; padding: 0; font-size: 14px; font-weight: bold; color: #bababa;"><?php echo date('d M Y') ?></h2>
													</td>
												</tr>
												<tr>
													<td valign="top" height="34" style="height: 34px; border-bottom-color: #d6d6d6; border-bottom-width: 1px; border-bottom-style: solid;">&nbsp;</td>
												</tr>
												<tr>
													<td valign="top" height="33" style="height: 33px;">&nbsp;</td>
												</tr>
												<tr>
													<td valign="top" width="100%">
														<table cellspacing="0" border="0" cellpadding="0" width="100%">
															<tr>
																<td valign="top">
																	<p style="margin: 0; margin-top: 7px; margin-bottom: 20px; padding: 0; font-size: 13px; font-weight: normal; color: #535353; line-height: 22px; text-align: justify;">
																		<?php echo $this->record['content'] ?> 
																	</p>
																</td>
															</tr>
														</table>
													</td>
												</tr>
												<tr>
													<td valign="top" height="40" bgcolor="#ffffff" style="height: 40px;">&nbsp;</td>
												</tr>
												<tr>
													<td valign="middle" height="58" style="height: 58px; vertical-align: middle; border-top-color: #d6d6d6; border-top-width: 1px; border-top-style: solid;">
														<p style="font-size: 11px; font-weight: bold; color: #8a8a8a; text-align: center;">
															Don't want to receive these newsletters anymore? Manage your <preferences style="color: #fd2323; text-decoration: none;">email preferences here</preferences>, or <unsubscribe style="color: #fd2323; text-decoration: none;">unsubscribe</unsubscribe>. 
														</p>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
									<!--/content-->
								</tr>
							</tbody>
						</table><!--/container-->
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>