<?php $this->headTitle()->prepend($this->translate('Edit product')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $attrGroups = $this->attrgroups;
    $attributes = $this->attributes;
    
//     var_dump($attrGroups);
//     die;
?>

<div class="row">
    <div class="col-lg-8">
        <h2><?php echo $this->translate('Product') ?></h2>
        <p><?php echo $this->translate('Create and product management') ?></p>
    </div>
    <div class="col-lg-4">
    	<div class="text-right">
		    <a href="/admin/product/add" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
		    <?php echo $this->formElement($form->get('submit')); ?>
		    <a href="/admin/product/" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
		</div>
	</div>
</div>

    <?php if ($this->error): ?>
        <div class="row">
	        <div class="col-lg-12">
	            <div class="alert alert-warning">
	                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
	            </div>
	        </div>
        </div>
    <?php endif ?>

	<div class="row">
		<div class="col-lg-12">
			<div class="tabbable tabs-left" id="tabs">
				<ul class="nav nav-tabs">
					<?php foreach ($attrGroups as $id => $group):?>
						<li><a data-toggle="tab" href="#tab<?php echo $id?>"><?php echo $this->translate($group);?></a></li>
					<?php endforeach;?>
				</ul>
				<div class="tab-content">
					<?php foreach ($attributes as $groupId => $group):?>
				    	<div class="tab-pane" id="tab<?php echo $groupId ?>">
					    	<div class="row">
					    		<?php foreach ($group as $data):?>
								        <div class="form-group">
					                        <?php echo $this->formLabel($form->get('attributes')->get($data['attribute']->getName())); ?>
					                        <?php echo $this->formElement($form->get('attributes')->get($data['attribute']->getName())); ?>
					                        <?php echo $this->formElementErrors($form->get('attributes')->get($data['attribute']->getName())); ?>
					                    </div>
				                <?php endforeach;?>
			                </div>
		                </div>
			        <?php endforeach;?>   
			   	</div>
			</div>
		</div>
	</div>
	
<?php echo $this->formElement($form->get('attribute_set_id')); ?>
<?php echo $this->formElement($form->get('type_id')); ?>
<?php echo $this->formElement($form->get('id')); ?>
<?php echo $this->form()->closeTag() ?>
