<?php $this->headTitle()->prepend($this->translate('Edit page')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-lg-8">
        <h2><?php echo $this->translate('Product') ?></h2>
        <p><?php echo $this->translate('Create and product management') ?></p>
    </div>
    <div class="col-lg-4">
    	<div class="text-right">
		    <a href="/admin/product/add" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
		    <?php echo $this->formElement($form->get('submit')); ?>
		    <a href="/admin/product/" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
		</div>
	</div>
</div>

    <?php if ($this->error): ?>
        <div class="row">
	        <div class="col-lg-12">
	            <div class="alert alert-warning">
	                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
	            </div>
	        </div>
        </div>
    <?php endif ?>

	<div class="row">
		<div class="col-lg-12">
			<div class="tabbable" id="tabs">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#tab10"><?php echo $this->translate('Main');?></a></li> 
					<li><a data-toggle="tab" href="#tab100"><?php echo $this->translate('Attributes');?></a></li> 
				</ul>
				<div class="tab-content">
				    <div class="tab-pane active" id="tab10">
				        <div class="form-group">
	                        <?php echo $this->formLabel($form->get('attributes')->get('name')); ?>
	                        <?php echo $this->formElement($form->get('attributes')->get('name')); ?>
	                        <?php echo $this->formElementErrors($form->get('attributes')->get('name')); ?>
	                    </div>
				    </div>
				    
				    <div class="tab-pane" id="tab100">
				        <?php foreach($this->attributes as $attribute): ?>
				        <?php if($attribute->getIsUserDefined()): ?>
    						<div class="form-group">
    	                        <?php echo $this->formRow($form->get('attributes')->get($attribute->getCode())); ?>
    	                    </div>
    	                <?php endif; ?>
	                    <?php endforeach;?>
				    </div>
			   	</div>
			</div>
		</div>
	</div>
	
<?php echo $this->formElement($form->get('attribute_set_id')); ?>
<?php echo $this->formElement($form->get('type_id')); ?>
<?php echo $this->formElement($form->get('id')); ?>
<?php echo $this->form()->closeTag() ?>
