<?php $this->headTitle()->prepend($this->translate('New Product')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'set')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-lg-8">
        <h2><?php echo $this->translate('Product') ?></h2>
        <p><?php echo $this->translate('Create a new product') ?></p>
    </div>
    <div class="col-lg-4">
    	<div class="text-right">
		    <a href="/admin/product/new" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
		    <?php echo $this->formElement($form->get('submit')); ?>
		    <a href="/admin/product/" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
		</div>
	</div>
</div>

    <?php if ($this->error): ?>
        <div class="row">
	        <div class="col-lg-12">
	            <div class="alert alert-warning">
	                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
	            </div>
	        </div>
        </div>
    <?php endif ?>

	<div class="row">
		<div class="col-lg-12">
					<div class="form-group">
                        <?php echo $this->formLabel($form->get('type_id')); ?>
                        <?php echo $this->formElement($form->get('type_id')); ?>
                        <?php echo $this->formElementErrors($form->get('type_id')); ?>
                    </div>
					<div class="form-group">
                        <?php echo $this->formLabel($form->get('attribute_set_id')); ?>
                        <?php echo $this->formElement($form->get('attribute_set_id')); ?>
                        <?php echo $this->formElementErrors($form->get('attribute_set_id')); ?>
                    </div>
		</div>
	</div>
	
<?php echo $this->formElement($form->get('id')); ?>
<?php echo $this->form()->closeTag() ?>
