<div class="navbar navbar-default navbar-fixed-bottom hidden-xs">
    <div class="col-lg-2">
        <?php echo $this->languages() ?>
    </div>
    <div class="col-lg-10">
		<ul class="nav navbar-nav pull-right">
		    <li><a href="#"><?php echo 'Mem: '.(memory_get_peak_usage(true)/1024)."KB"?></a></li>
		    <li><a href="https://twitter.com/shine_software" data-show-count="false" data-size="large"><i class="fa fa-twitter"></i> <?php echo sprintf($this->translate('Follow us %s'), '@shine_software') ?></a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="glyphicon glyphicon-question-sign"></i> <?php echo $this->translate('Help')?></a>
                <ul class="dropdown-menu pull-right">
                    <li class="dropdown"><a href="#" target="_blank"><i class="glyphicon glyphicon-question-sign"></i> <?php echo $this->translate('How-to translate the project')?></a></li>
                    <li class="divider"></li>
                    <li class="dropdown"><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JK3ERUVCWMQ8C" target="_blank"><i class="glyphicon glyphicon-euro"></i> <?php echo $this->translate('Donate')?></a></li>
        		    <li class="divider"></li>
        		    <li class="dropdown"><a href="#" target="_blank"><?php printf($this->translate('About %s'), $this->settings('name'))?></a></li>
                </ul>
            </li>
		</ul>
	</div>
</div>
