<?php $this->headTitle($this->settings('name') . " " . $this->translate('Administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/administration.css'); ?>
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/administration.js'); ?>
        
<?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) ?>

<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>