<div class="navbar navbar-default navbar-fixed-bottom hidden-xs">
    <div class="col-lg-2">
        <?php echo $this->languages() ?>
    </div>
    <div class="col-lg-10">
		<ul class="nav navbar-nav pull-right">
		    <li><a href="#"><?php echo 'Mem: '.(memory_get_peak_usage(true)/1024)."KB"?></a></li>
		    <li><a href="https://twitter.com/shine_software" data-show-count="false" data-size="large"><i class="fa fa-twitter"></i> <?php echo sprintf($this->translate('Follow us %s'), '@shine_software') ?></a></li>
		    <li><a href="https://twitter.com/intent/tweet?screen_name=shine_software&text=Thank%20you%20guys%20for%20@shineisp%20downloaded%20from%20@github.%20I%20have%20installed%20your%20%23isp%20%23software%20in%20our%20server%20at%20<?php echo $_SERVER["SERVER_NAME"] ?>!" data-text="" data-size="large" data-related="shine_software"><i class="fa fa-twitter"></i> <?php echo $this->translate('Tweet')?></a></li>

            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="glyphicon glyphicon-question-sign"></i> <?php echo $this->translate('Help')?></a>
                <ul class="dropdown-menu pull-right">
                    <li class="dropdown"><a href="http://www.shineisp.com/translating-shineisp/" target="_blank"><i class="glyphicon glyphicon-question-sign"></i> <?php echo $this->translate('How-to translate the project')?></a></li>
                    <li class="divider"></li>
                    <li class="dropdown"><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JK3ERUVCWMQ8C" target="_blank"><i class="glyphicon glyphicon-euro"></i> <?php echo $this->translate('Donate')?></a></li>
                    <li class="dropdown"><a href="http://groups.google.com/group/shineisp" target="_blank"><i class="glyphicon glyphicon-volume-down"></i> <?php echo $this->translate('Group/Forum')?></a></li>
        		    <li class="dropdown"><a href="https://github.com/shinesoftware/shineisp" target="_blank"><i class="glyphicon glyphicon-align-left"></i> <?php echo $this->translate('Source Files')?></a></li>
        		    <li class="divider"></li>
        		    <li class="dropdown"><a href="http://www.shineisp.com/" target="_blank"><?php echo $this->translate('About ShineISP')?></a></li>
                </ul>
            </li>
		</ul>
	</div>
</div>