
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            
            <h2><?php echo $this->translate('Oops this page has been not found. However you should not despair!' ) ?></h2>
            <p>
                <?php if (isset($this->reason) && $this->reason): ?>
                	<?php echo $this->reason ?> - <?php echo $this->message ?><br/>
                <?php endif ?>
                	
                <?php if (isset($this->controller) && $this->controller): ?>
            		<?php echo $this->escapeHtml($this->controller)?>
            		<?php
            		    if (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller) {
            		        echo '(' . sprintf('resolves to %s', $this->escapeHtml($this->controller_class)) . ')';
            		    }
            		?>
                <?php endif ?>
            </p>
            <p><?php echo $this->translate('Click one of these buttons to solve the problem.') ?></p>
            <p><a class='btn btn-success' href='<?php echo $this->url('home') ?>'><?php echo $this->translate('Homepage') ?></a>
            <a class='btn btn-success' href='#'><?php echo $this->translate('Contact us') ?></a></p>
            	
            <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
            
            <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
            <hr />
            <h2>Additional information:</h2>
            <h3><?php echo get_class($this->exception); ?></h3>
            <dl>
            	<dt>File:</dt>
            	<dd>
            		<pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
            	</dd>
            	<dt>Message:</dt>
            	<dd>
            		<pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
            	</dd>
            	<dt>Stack trace:</dt>
            	<dd>
            		<pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
            	</dd>
            </dl>
            <?php
                    $e = $this->exception->getPrevious();
                    if ($e) :
                        ?>
            <hr />
            <h2>Previous exceptions:</h2>
            <ul class="unstyled">
                <?php while($e) : ?>
                <li>
            		<h3><?php echo get_class($e); ?></h3>
            		<dl>
            			<dt>File:</dt>
            			<dd>
            				<pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
            			</dd>
            			<dt>Message:</dt>
            			<dd>
            				<pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
            			</dd>
            			<dt>Stack trace:</dt>
            			<dd>
            				<pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
            			</dd>
            		</dl>
            	</li>
                <?php
            		$e = $e->getPrevious();
                    endwhile;
            	?>
            </ul>
            <?php endif; ?>
            
            <?php endif ?>
            
            <?php endif ?>
        </div>
    </div>
</div>