<?php $this->headTitle()->prepend($this->translate('Cms - List of all pages')); ?>

<div class="row header">
    <div class="col-lg-10">
        <div class="page-header">
            <h1><i class="fa fa-file-text-o"></i> <?php echo $this->translate('Cms Pages') ?> <small><?php echo $this->translate('Create new site content') ?></small></h1>
            <?php echo $this->translate('This is the list of all pages of this site.') ?>
        </div>
    </div>
    <?php if ($this->error): ?>
        <div class="col-lg-12">
            <div class="alert alert-warning">
                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
            </div>
        </div>
    <?php endif ?>
</div>

<?php echo $this->grid ?>

<hr />
<a href="/admin/cmspages/add">&raquo <?php echo $this->translate('Add page') ?></a>