<?php $this->headTitle()->prepend($this->translate('Cms Settings')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-lg-12">
        <h2><?php echo $this->translate('Cms Settings') ?></h2>
        <p><?php echo $this->translate('Set your preferences for the Cms section of the website') ?></p>
    </div>
</div>

<?php if ($this->error): ?>
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-warning">
                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
            </div>
        </div>
    </div>
<?php endif ?>

<div class="row">
	<div class="col-lg-12">
	    <div class="tab-pane active" id="tab1">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('defaultlayout')); ?>
                <?php echo $this->formElement($form->get('defaultlayout')); ?>
                <?php echo $this->formElementErrors($form->get('defaultlayout')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('postperpage')); ?>
                <?php echo $this->formElement($form->get('postperpage')); ?>
                <?php echo $this->formElementErrors($form->get('postperpage')); ?>
            </div>
        </div>
        
        <div class="text-center"><?php echo $this->formElement($form->get('submit')); ?></div>
	</div>
</div>

<?php echo $this->form()->closeTag() ?>
