
<ul class="nav navbar-nav navbar-right" id="languages">
    <li class="dropdown">
    	<a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-flag"></i> <span class="hidden-sm hidden-md"><?php echo !empty($this->selectedLanguage) ? $this->selectedLanguage : $this->translate('Language') ?></span> <b class="caret"></b></a>
    	<ul class="dropdown-menu">
    	    <?php $languages = $this->languages?>
    	    <?php foreach ($languages as $code => $translation): ?>
			    <li><a href="/<?php echo $code?>"><i class="fa fa-flag"></i> <?php echo $translation ?></a></li>
			<?php endforeach; ?>
        </ul>
    </li>
</ul>