<ul class="nav navbar-nav navbar-right" id="languages">
    <li class="dropdown">
    	<a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="fa fa-flag"></i> <?php echo $this->selectedLanguage ?> <b class="caret"></b></a>
    	<ul class="dropdown-menu">
    	    <?php $languages = $this->languages?>
    	    <?php foreach ($languages as $id => $translation): ?>
			    <li><a href="/switch/<?php echo $id?>"><i class="fa fa-flag"></i> <?php echo $translation ?></a></li>
			<?php endforeach; ?>
        </ul>
    </li>
</ul>