<?php $this->headTitle()->prepend($this->translate('Edit attribute')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-lg-8">
        <h2><?php echo $this->translate('Attribute') ?></h2>
        <p><?php echo $this->translate('Handle a the product attribute') ?></p>
    </div>
    <div class="col-lg-4">
    	<div class="text-right">
		    <a href="/admin/product/attributes/add" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
		    <?php echo $this->formElement($form->get('submit')); ?>
		    <a href="/admin/product/attributes/" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
		</div>
	</div>
</div>

    <?php if ($this->error): ?>
        <div class="row">
	        <div class="col-lg-12">
	            <div class="alert alert-warning">
	                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
	            </div>
	        </div>
        </div>
    <?php endif ?>

	<div class="row">
		<div class="col-lg-12">
			<div class="tabbable" id="tabs">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#tab10"><?php echo $this->translate('Main');?></a></li> 
				</ul>
				<div class="tab-content">
				    <div class="tab-pane active" id="tab10">
						<div class="form-group">
	                        <?php echo $this->formLabel($form->get('name')); ?>
	                        <?php echo $this->formElement($form->get('name')); ?>
	                        <?php echo $this->formElementErrors($form->get('name')); ?>
	                    </div>
				    </div>
			   	</div>
			</div>
		</div>
	</div>
	
<?php echo $this->formElement($form->get('id')); ?>
<?php echo $this->form()->closeTag() ?>
