<?php $page = $this->page; ?>
<?php $parent = $this->parent; ?>

<?php echo $this->partial('cms/partial/header'); ?> 

<?php echo $this->blocks($page, 'startbody'); ?>

<div class="container">
    <div class="row"> 
    	<?php echo $this->blocks($page, 'beforecontent'); ?>
    
    	<div class="col-lg-12">
    		<?php echo $this->blocks($page, 'contentstart'); ?>
    		<?php echo $page->getContent() ?>
    		<?php echo $this->blocks($page, 'contentend'); ?>
    	</div>
    	
    	<?php echo $this->blocks($page, 'aftercontent'); ?>
    </div>
</div> 
<?php echo $this->blocks($page, 'endbody'); ?>