<h2><?php echo $this->translate('Our latest')?></h2>
<?php $pages = $this->pages; ?>

<ul class="media-list">
	<?php foreach ($pages as $page): ?>	
		<li class="media">
    		<div class="media-body">
      			<h4 class="media-heading"> <a href="/cms/<?php echo $page->getUri(); ?>.html"><?php echo $page->getTitle() ?></a></h4>
      			<?php echo $this->tags($page->getTags()) ?> 
      			<?php echo $this->extract($page->getContent(), 300) ?>
      			<p class="text-right">
	      			<span class="label label-warning"><?php echo $page->category ?></span>
	      			<span class="label label-default"><?php echo $this->datetime($page->getCreatedat()) ?></span>
	      		</p>
    		</div>
  		</li>
  	<?php endforeach;?>
</ul>
