<?php echo $this->doctype(); ?>

<html lang="<?php echo \Locale::getPrimaryLanguage(Locale::getDefault())?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <?php echo $this->partial('partial/head.phtml'); ?> 
    </head>
    <body>
        <?php echo !$this->settings('active') ? "<div class='alert alert-warning'>" . $this->translate('This website is on maintenance mode') . "</div>" : null?>
        <?php echo $this->partial('partial/header.phtml'); ?> 
        <div class="wrapper">
            <?php echo $this->flashMessage(); ?>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->partial('footer'); ?> 
        <?php echo $this->inlineScript(); ?>
        <?php echo $this->settings('bodyscript')?>
    </body>
</html>
