<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->partial('partial/head.phtml'); ?> 
    </head>
    <body>
        <?php echo $this->partial('partial/header.phtml'); ?> 	
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <?php echo $this->flashMessage(); ?>
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
