<div class="container">
    <div class="row header">
        <div class="col-lg-12">
            <h2><?php echo $this->translate('Forgot your password?') ?></h2>
            <p><?php echo $this->translate('Reset your password right now an email will be send to your mailbox to confirm.') ?></p>
        </div>
    </div>
    
    <?php
    $form = $this->forgotForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/forgotpassword'));
    $form->setAttribute('method', 'post');
    ?>
    
    <?php echo $this->form()->openTag($form) ?>
    
        <?php echo $this->formLabel($form->get('email')) ?>
        <div style="margin-bottom: 25px" class="input-group">
            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
            <?php echo $this->FormElement($form->get('email')->setAttributes(array('class' => 'form-control', 'placeholder'=>$this->translate('type here your email address')))) ?>
        </div>
        <?php echo $this->formElementErrors($form->get('email')) ?>
    
        <div class="form-group">
            <?php echo $this->formInput($form->get('submit')->setAttributes(array('class' => 'btn btn-success', 'value' => $this->translate('Reset password')))); ?> 
        </div>
        <div class="form-group">
            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                <a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Back to login?')?></a>
            </div>
        </div>    
                
    <?php echo $this->form()->closeTag() ?>
</div>