<div class="row header">
    <div class="col-lg-12">
        <h2><?php echo sprintf($this->translate('Change Password for %s'), $this->escapeHtml($this->email)) ?></h2>
        <p><?php echo $this->translate('Reset your password right now.') ?></p>
    </div>
</div>

<?php

$form = $this->resetForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/resetpassword', array('userId' => $this->userId, 'token' => $this->token)));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

?>
<div class="row">
    <div class="col-lg-12">

        <?php echo $this->formLabel($form->get('newCredential')) ?>
        <div style="margin-bottom: 25px" class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <?php echo $this->FormElement($form->get('newCredential')->setAttributes(array('class' => 'form-control', 'placeholder'=>$this->translate('type here your new password')))) ?>
        </div>
        <?php echo $this->formElementErrors($form->get('newCredential')) ?>
        
        <?php echo $this->formLabel($form->get('newCredentialVerify')) ?>
        <div style="margin-bottom: 25px" class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <?php echo $this->FormElement($form->get('newCredentialVerify')->setAttributes(array('class' => 'form-control', 'placeholder'=>$this->translate('type again your new password')))) ?>
        </div>
        <?php echo $this->formElementErrors($form->get('newCredentialVerify')) ?>
        
        <div class="form-group">
            <?php echo $this->formInput($form->get('submit')->setAttributes(array('class' => 'btn btn-success', 'value' => $this->translate('Save')))); ?> 
        </div>
        <div class="form-group">
            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                <a href="/user"><?php echo $this->translate('Go back')?></a>
            </div>
        </div>    
    </div>    
</div>    

<?php echo $this->form()->closeTag(); ?>
