<div class="row header">
    <div class="col-lg-12">
        <h2><?php echo sprintf($this->translate('Reset link has been sent to %s'), $this->escapeHtml($this->email)) ?></h2>
        <p><?php echo $this->translate('Click the link to confirm that the address is correct.') ?></p>
    </div>
</div>
<p><?php echo $this->translate('A reminder has been sent to your e-mail address') ?> <?php echo $this->escapeHtml($this->email); ?></p>

<a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Back to login?')?></a>
