<?php $this->headTitle()->prepend($this->translate('Edit attribute set')); ?>

<?php 
    $form = $this->form;
    $attributeGroups = $this->attributegroups;
    $attributes = $this->attributes;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $current_group = null;
?>

<div class="row">
    <div class="col-lg-8">
        <h2><?php echo $this->translate('Attribute Set') ?></h2>
        <p><?php echo $this->translate('Handle a the product attribute sets') ?></p>
    </div>
    <div class="col-lg-4">
    	<div class="text-right">
		    <a href="/admin/product/sets/add" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
		    <?php echo $this->formElement($form->get('submit')); ?>
		    <a href="/admin/product/sets/" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
		</div>
	</div>
</div>

    <?php if ($this->error): ?>
        <div class="row">
	        <div class="col-lg-12">
	            <div class="alert alert-warning">
	                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
	            </div>
	        </div>
        </div>
    <?php endif ?>

	<div class="row">
		<div class="col-lg-12">
			<div class="tabbable" id="tabs">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#tab10"><?php echo $this->translate('Main');?></a></li> 
				</ul>
				<div class="tab-content">
				    <div class="tab-pane active" id="tab10">
						
						
	                    <div class="row">
		                    <div class="col-lg-6">
		                        <div id="tree">
                                    <ul id="treeData" style="display: none;">
                                    <?php foreach ($attributes as $attribute_set): ?>
                                        <?php foreach ($attribute_set as $group => $attrs): ?>
                                            <li class="folder expanded"><?php echo $group;?>
                                                <ul>
                                                    <?php foreach ($attrs as $attribute): ?>
        												<li id="id<?php echo $attribute->attrid; ?>" class=""><?php echo $attribute->attribute ?></li>
        											<?php endforeach;?>
    										    </ul>
    										</li>
       									<?php endforeach;?>
    								<?php endforeach;?>
                                    </ul>
                                  </div>
		                    </div>
		                    
		                    
		                    
		                    
<!-- 		                     <div id="tree"> -->
<!--                                    <ul id="treeData" style="display: none;"> -->
<!--                                       <li id="id1" title="Look, a tool tip!">item1 with key and tooltip -->
<!--                                       <li id="id2">item2 -->
<!--                                       <li id="id3" class="folder">Folder <em>with some</em> children -->
<!--                                         <ul> -->
<!--                                           <li id="id3.1">Sub-item 3.1 -->
<!--                                             <ul> -->
<!--                                               <li id="id3.1.1">Sub-item 3.1.1 -->
<!--                                               <li id="id3.1.2">Sub-item 3.1.2 -->
<!--                                             </ul> -->
<!--                                           <li id="id3.2">Sub-item 3.2 -->
<!--                                             <ul> -->
<!--                                               <li id="id3.2.1">Sub-item 3.2.1 -->
<!--                                               <li id="id3.2.2">Sub-item 3.2.2 -->
<!--                                             </ul> -->
<!--                                         </ul> -->
<!--                                       <li id="id4" class="expanded">Document with some children (expanded on init) -->
<!--                                         <ul> -->
<!--                                           <li id="id4.1"  class="active focused">Sub-item 4.1 (active and focus on init) -->
<!--                                             <ul> -->
<!--                                               <li id="id4.1.1">Sub-item 4.1.1 -->
<!--                                               <li id="id4.1.2">Sub-item 4.1.2 -->
<!--                                             </ul> -->
<!--                                           <li id="id4.2">Sub-item 4.2 -->
<!--                                             <ul> -->
<!--                                               <li id="id4.2.1">Sub-item 4.2.1 -->
<!--                                               <li id="id4.2.2">Sub-item 4.2.2 -->
<!--                                             </ul> -->
<!--                                         </ul> -->
<!--                                     </ul> -->
<!--                                   </div> -->
		                    
		                    
		                    <div class="col-lg-6">
	                            <div class="form-set">
        	                        <?php echo $this->formLabel($form->get('name')); ?>
        	                        <?php echo $this->formElement($form->get('name')); ?>
        	                        <?php echo $this->formElementErrors($form->get('name')); ?>
        	                    </div>
        	                    <div class="form-set">
        	                        <?php echo $this->formLabel($form->get('attributes')); ?>
        	                        <?php echo $this->formElement($form->get('attributes')); ?>
        	                        <?php echo $this->formElementErrors($form->get('attributes')); ?>
        	                    </div>
	                        </div>
	                    </div>
						
                        						
				    </div>
			   	</div>
			</div>
		</div>
	</div>
	
<?php echo $this->formElement($form->get('id')); ?>
<?php echo $this->form()->closeTag() ?>
