<?php $this->headTitle()->prepend($this->translate('Edit language')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array( 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-lg-8">
        <h2><?php echo $this->translate('Language Preference') ?></h2>
        <p><?php echo $this->translate('Edit your language preferences.') ?></p>
    </div>
    <div class="col-lg-4">
    	<div class="text-right">
		    <a href="/admin/languages/add" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
		    <?php echo $this->formElement($form->get('submit')); ?>
		    <a href="/admin/languages" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
		</div>
	</div>
</div>

    <?php if ($this->error): ?>
        <div class="row">
	        <div class="col-lg-12">
	            <div class="alert alert-warning">
	                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
	            </div>
	        </div>
        </div>
    <?php endif ?>

<div class="row">
	<div class="col-lg-12">
		<div class="tabbable" id="tabs">
			<ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			</ul>
			<div class="tab-content">
			    <div class="tab-pane active" class="tab-pane" id="tab1">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('language')); ?>
                        <?php echo $this->formElement($form->get('language')); ?>
                        <?php echo $this->formElementErrors($form->get('language')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('code')); ?>
                        <?php echo $this->formElement($form->get('code')); ?>
                        <?php echo $this->formElementErrors($form->get('code')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('locale')); ?>
                        <?php echo $this->formElement($form->get('locale')); ?>
                        <?php echo $this->formElementErrors($form->get('locale')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('base')); ?>
                        <?php echo $this->formElement($form->get('base')); ?>
                        <?php echo $this->formElementErrors($form->get('base')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('active')); ?>
                        <?php echo $this->formElement($form->get('active')); ?>
                        <?php echo $this->formElementErrors($form->get('active')); ?>
                    </div>
                </div>
		   	</div>
		</div>
	</div>
</div>
<?php echo $this->formElement($form->get('id')); ?>

<?php echo $this->form()->closeTag() ?>
