<?php $this->headTitle()->prepend($this->translate('Settings - Languages')); ?>

<div class="row header">
    <div class="col-lg-10">
        <div class="page-header">
            <h1><i class="fa fa-language"></i> <?php echo $this->translate('Languages') ?> <small><?php echo $this->translate('Set a new language for your site') ?></small></h1>
            <?php echo $this->translate('This is the list of all languages of this site.') ?>
        </div>
    </div>
    <?php if ($this->error): ?>
        <div class="col-lg-12">
            <div class="alert alert-warning">
                <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
            </div>
        </div>
    <?php endif ?>
</div>

<?php echo $this->grid ?>

<hr />
<a href="/admin/languages/add">&raquo <?php echo $this->translate('Add language') ?></a>